In [1]:
import pandas as pd
import numpy as np
import csv

In [2]:
df = pd.read_csv('Joined_Postcode.csv',na_values='')

In [4]:
df.head(4)

,Postcode,incorporationdate,companycategory,companystatus,CompanyCategory,CompanyStatus,IncorporationDate,SIC_2013,SIC2018,SICcombine,usertype,oa11cd,lsoa11cd,msoa11cd,ladcd,lsoa11nm,msoa11nm,ladnm,FID
0,06 830,28/05/2008,Limited Partnership,Active,Limited Partnership,Active,28/05/2008,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,06 830,28/05/2008,Limited Partnership,Active,Limited Partnership,Active,28/05/2008,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,06 830,28/05/2008,Limited Partnership,Active,Limited Partnership,Active,28/05/2008,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,06 830,28/05/2008,Limited Partnership,Active,Limited Partnership,Active,28/05/2008,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.shape

(1048575, 19)

In [3]:
df_post= df.set_index('Postcode')

In [12]:
df_post[['SIC_2013','SIC2018','SICcombine']]

            SIC_2013  SIC2018  SICcombine
Postcode
06 830             0        0         NaN
06 830             0        0         NaN
06 830             0        0         NaN
06 830             0        0         NaN
06 830             0        0         NaN
06 830             0        0         NaN
06 830             0        0         NaN
06 830             0        0         NaN
06 830             0        0         NaN
06 830             0        0         NaN
19808 USA          0        0         NaN
20 006             0        0         NaN
20004-2505         0        0         NaN
3 7BG              0        0         NaN
60 606             0        0         NaN
8                  0        0         NaN
AB1 1PU        52290    52290     52290.0
AB1 1PU        50300    50300     50300.0
AB1 1PU        52290    50200         NaN
AB1 1PU        50200    50200     50200.0
AB1 1PU        96090    96090     96090.0
AB1 1PU        52290    52290     52290.0
AB1 1PU        70100    70100     70100.0
AB1 1UL        96090    96090     96090.0
AB1 1UL        41100    41100     41100.0
AB1 1XL            0        0         NaN
AB1 1XL            0        0         NaN
AB1 1YL            0        0         NaN
AB1 1YL            0        0         NaN
AB1 1YL            0        0         NaN
...              ...      ...         ...
W14 9JS        99999    99999     99999.0
W14 9JU        70229    70229     70229.0
W14 9JX        98000    98000     98000.0
W14 9JX        73120    73120     73120.0
W14 9JX        74909    74909     74909.0
W14 9JY        98000    98000     98000.0
W14 9JY        98000    98000     98000.0
W14 9JY        98000    98000     98000.0
W14 9LB        58190    58190     58190.0
W14 9LE        98000    98000     98000.0
W14 9LE        62090    62090     62090.0
W14 9LJ        68320    68320     68320.0
W14 9LJ            0        0         NaN
W14 9LJ            0        0         NaN
W14 9LP        59112    59112     59112.0
W14 9LS        59111    59111     59111.0
W14 9LS        98000    98000     98000.0
W14 9LX        98000    98000     98000.0
W14 9NE        62020    62020     62020.0
W14 9NE        41202    41202     41202.0
W14 9NE        68201    68201     68201.0
W14 9NH        78200    78200     78200.0
W14 9NH        78200    78200     78200.0
W14 9NL        98000    98000     98000.0
W14 9NL        94990    94990     94990.0
W14 9NL        74990    74990     74990.0
W14 9NL        98000    98000     98000.0
W14 9NL        73110    73110     73110.0
W14 9NL        74909    74909     74909.0
W14 9NL        81299    81299     81299.0

[1048575 rows x 3 columns]

In [118]:
SICdata=pd.read_csv('SIC_integer.csv',na_values='')

In [119]:
SICdata.head(5)

,incorporationdate,postcode,companycategory,companystatus,CompanyCategory,CompanyStatus,IncorporationDate,SIC_2013,SIC2018,SICcombine
0,1992-05-12,SE4 1NQ,Private Limited Company,Active,Private Limited Company,Active,12/05/1992,90010,90010,90010.0
1,1999-07-22,TN11 9PL,Private Limited Company,Active,Private Limited Company,Active,22/07/1999,70229,70229,70229.0
2,2007-11-28,GU21 5TS,Private Limited Company,Active,Private Limited Company,Active,28/11/2007,99999,99999,99999.0
3,2008-01-15,WD6 1JD,Private Limited Company,Active,Private Limited Company,Active,15/01/2008,56101,56101,56101.0
4,2002-07-25,OL2 7DD,Private Limited Company,Active,Private Limited Company,Active,25/07/2002,86230,86230,86230.0

In [16]:
SICdata.shape

(1148256, 10)

In [2]:
postcode = pd.read_csv('/Users/jyothigupta/Documents/UCL/GIS/GIS class/week 1/Postcode.csv',na_values='')
postcode.head(5)

/Users/jyothigupta/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,pcd7,pcd8,pcds,dointr,doterm,usertype,oa11cd,lsoa11cd,msoa11cd,ladcd,lsoa11nm,msoa11nm,ladnm,ladnmw,FID
0,AB118RJ,AB11 8RJ,AB11 8RJ,199606,0,0,S00089089,S01006635,S02001258,S12000033,Torry East - 05,Torry East,Aberdeen City,NaN,4001
1,AB116WH,AB11 6WH,AB11 6WH,199606,0,0,S00090554,S01006591,S02001251,S12000033,Ferryhill North - 01,Ferryhill North,Aberdeen City,NaN,4002
2,AB116YW,AB11 6YW,AB11 6YW,199606,0,1,S00090575,S01006582,S02001249,S12000033,City Centre West - 01,City Centre West,Aberdeen City,NaN,4003
3,AB118RL,AB11 8RL,AB11 8RL,199606,0,0,S00089089,S01006635,S02001258,S12000033,Torry East - 05,Torry East,Aberdeen City,NaN,4004
4,AB118YB,AB11 8YB,AB11 8YB,199707,199801,1,S00090467,S01006636,S02001258,S12000033,Torry East - 06,Torry East,Aberdeen City,NaN,4005

In [3]:
postcode.shape

(2616838, 15)

In [15]:
postcode= postcode.set_index('pcds')
postcode.head(4)

,pcd7,pcd8,dointr,doterm,usertype,oa11cd,lsoa11cd,msoa11cd,ladcd,lsoa11nm,msoa11nm,ladnm,ladnmw,FID
pcds,,,,,,,,,,,,,,
AB11 8RJ,AB118RJ,AB11 8RJ,199606,0,0,S00089089,S01006635,S02001258,S12000033,Torry East - 05,Torry East,Aberdeen City,NaN,4001
AB11 6WH,AB116WH,AB11 6WH,199606,0,0,S00090554,S01006591,S02001251,S12000033,Ferryhill North - 01,Ferryhill North,Aberdeen City,NaN,4002
AB11 6YW,AB116YW,AB11 6YW,199606,0,1,S00090575,S01006582,S02001249,S12000033,City Centre West - 01,City Centre West,Aberdeen City,NaN,4003
AB11 8RL,AB118RL,AB11 8RL,199606,0,0,S00089089,S01006635,S02001258,S12000033,Torry East - 05,Torry East,Aberdeen City,NaN,4004

In [12]:
postcode.head(3)

,pcd7,pcd8,pcds,dointr,doterm,usertype,oa11cd,lsoa11cd,msoa11cd,ladcd,lsoa11nm,msoa11nm,ladnm,ladnmw,FID
0,AB118RJ,AB11 8RJ,AB11 8RJ,199606,0,0,S00089089,S01006635,S02001258,S12000033,Torry East - 05,Torry East,Aberdeen City,NaN,4001
1,AB116WH,AB11 6WH,AB11 6WH,199606,0,0,S00090554,S01006591,S02001251,S12000033,Ferryhill North - 01,Ferryhill North,Aberdeen City,NaN,4002
2,AB116YW,AB11 6YW,AB11 6YW,199606,0,1,S00090575,S01006582,S02001249,S12000033,City Centre West - 01,City Centre West,Aberdeen City,NaN,4003

In [4]:
data = pd.read_csv('ukpostcodes.csv',na_values='')

In [5]:
data_post= data.set_index('postcode')

In [16]:
data_post.head(4)

          id   latitude  longitude
postcode
AB10 1XG   1  57.144165  -2.114848
AB10 6RN   2  57.137880  -2.121487
AB10 7JB   3  57.124274  -2.127190
AB11 5QN   4  57.142701  -2.093295

In [17]:
data_post.shape

(1765734, 3)

In [18]:
joined = data_post.join(postcode)

In [19]:
joined.shape

(1765734, 17)

In [20]:
joined.head(4)

,id,latitude,longitude,pcd7,pcd8,dointr,doterm,usertype,oa11cd,lsoa11cd,msoa11cd,ladcd,lsoa11nm,msoa11nm,ladnm,ladnmw,FID
postcode,,,,,,,,,,,,,,,,,
AB10 1XG,1,57.144165,-2.114848,AB101XG,AB10 1XG,199606.0,0.0,0.0,S00088970,S01006571,S02001247,S12000033,West End North - 01,West End North,Aberdeen City,NaN,3015.0
AB10 6RN,2,57.137880,-2.121487,AB106RN,AB10 6RN,199606.0,0.0,0.0,S00089205,S01006576,S02001248,S12000033,West End South - 02,West End South,Aberdeen City,NaN,3146.0
AB10 7JB,3,57.124274,-2.127190,AB107JB,AB10 7JB,199606.0,0.0,0.0,S00089357,S01006530,S02001239,S12000033,Garthdee - 05,Garthdee,Aberdeen City,NaN,3489.0
AB11 5QN,4,57.142701,-2.093295,AB115QN,AB11 5QN,199606.0,0.0,0.0,S00090582,S01006587,S02001250,S12000033,City Centre East - 01,City Centre East,Aberdeen City,NaN,3876.0

In [21]:
joined

,id,latitude,longitude,pcd7,pcd8,dointr,doterm,usertype,oa11cd,lsoa11cd,msoa11cd,ladcd,lsoa11nm,msoa11nm,ladnm,ladnmw,FID
postcode,,,,,,,,,,,,,,,,,
AB10 1XG,1,57.144165,-2.114848,AB101XG,AB10 1XG,199606.0,0.0,0.0,S00088970,S01006571,S02001247,S12000033,West End North - 01,West End North,Aberdeen City,NaN,3015.0
AB10 6RN,2,57.137880,-2.121487,AB106RN,AB10 6RN,199606.0,0.0,0.0,S00089205,S01006576,S02001248,S12000033,West End South - 02,West End South,Aberdeen City,NaN,3146.0
AB10 7JB,3,57.124274,-2.127190,AB107JB,AB10 7JB,199606.0,0.0,0.0,S00089357,S01006530,S02001239,S12000033,Garthdee - 05,Garthdee,Aberdeen City,NaN,3489.0
AB11 5QN,4,57.142701,-2.093295,AB115QN,AB11 5QN,199606.0,0.0,0.0,S00090582,S01006587,S02001250,S12000033,City Centre East - 01,City Centre East,Aberdeen City,NaN,3876.0
AB11 6UL,5,57.137547,-2.112233,AB116UL,AB11 6UL,199606.0,0.0,0.0,S00090560,S01006597,S02001251,S12000033,Ferryhill North - 07,Ferryhill North,Aberdeen City,NaN,3834.0
AB11 8RQ,6,57.135978,-2.072115,AB118RQ,AB11 8RQ,199606.0,0.0,0.0,S00089114,S01006631,S02001258,S12000033,Torry East - 01,Torry East,Aberdeen City,NaN,4068.0
AB12 3FJ,7,57.098003,-2.077438,AB123FJ,AB12 3FJ,199606.0,0.0,0.0,S00090233,S01006619,S02001256,S12000033,Cove North - 01,Cove North,Aberdeen City,NaN,4536.0
AB12 4NA,8,57.064273,-2.130018,AB124NA,AB12 4NA,199606.0,0.0,0.0,S00092225,S01006851,S02001295,S12000034,Banchory-Devenick and Findon - 04,Banchory-Devenick and Findon,Aberdeenshire,NaN,5068.0
AB12 5GL,9,57.081938,-2.246567,AB125GL,AB12 5GL,199606.0,0.0,0.0,S00091322,S01006853,S02001296,S12000034,"Dunecht, Durris and Drumoak - 01","Dunecht, Durris and Drumoak",Aberdeenshire,NaN,5189.0
AB12 9SP,10,57.148707,-2.097806,AB129SP,AB12 9SP,200502.0,0.0,0.0,S00090540,S01006646,S02001261,S12000033,George Street - 02,George Street,Aberdeen City,NaN,5214.0
AB14 0TQ,11,57.101557,-2.268486,AB140TQ,AB14 0TQ,199606.0,0.0,0.0,S00090294,S01006507,S02001236,S12000033,Culter - 02,Culter,Aberdeen City,NaN,5611.0
AB15 5HB,12,57.147428,-2.147266,AB155HB,AB15 5HB,199606.0,0.0,0.0,S00089703,S01006572,S02001247,S12000033,West End North - 02,West End North,Aberdeen City,NaN,5895.0
AB15 6NA,13,57.151797,-2.185398,AB156NA,AB15 6NA,199606.0,0.0,0.0,S00088959,S01006737,S02001275,S12000033,Kingswells - 06,Kingswells,Aberdeen City,NaN,6387.0
AB15 8BA,14,57.135624,-2.175239,AB158BA,AB15 8BA,199606.0,0.0,0.0,S00089394,S01006551,S02001243,S12000033,Hazlehead - 05,Hazlehead,Aberdeen City,NaN,6487.0
AB15 8UF,15,57.154006,-2.224402,AB158UF,AB15 8UF,199606.0,0.0,0.0,S00090946,S01006735,S02001275,S12000033,Kingswells - 04,Kingswells,Aberdeen City,NaN,6768.0
AB15 9SE,16,57.118648,-2.174251,AB159SE,AB15 9SE,200106.0,0.0,0.0,S00089428,S01006523,S02001238,S12000033,"Cults, Bieldside and Milltimber East - 06","Cults, Bieldside and Milltimber Eas",Aberdeen City,NaN,7087.0
AB16 5ST,17,57.163466,-2.159333,AB165ST,AB16 5ST,199606.0,0.0,0.0,S00089845,S01006722,S02001273,S12000033,Northfield - 04,Northfield,Aberdeen City,NaN,7172.0
AB16 6SZ,18,57.158751,-2.165215,AB166SZ,AB16 6SZ,199606.0,0.0,0.0,S00089990,S01006713,S02001271,S12000033,Sheddocksley - 06,Sheddocksley,Aberdeen City,NaN,7330.0
AB16 7NX,19,57.168438,-2.161636,AB167NX,AB16 7NX,199606.0,0.0,0.0,S00090028,S01006724,S02001273,S12000033,Northfield - 06,Northfield,Aberdeen City,NaN,7414.0
AB21 0AL,20,57.263420,-2.158605,AB210AL,AB21 0AL,200910.0,0.0,0.0,S00091112,S01006950,S02001311,S12000034,Newmachar and Fintray - 05,Newmachar and Fintray,Aberdeenshire,NaN,11018.0
AB21 0TF,21,57.221883,-2.273318,AB210TF,AB21 0TF,199606.0,0.0,0.0,S00088967,S01006755,S02001278,S12000033,Dyce - 07,Dyce,Aberdeen City,NaN,11117.0
AB21 7LD,22,57.212136,-2.185602,AB217LD,AB21 7LD,199606.0,0.0,0.0,S00090886,S01006750,S02001278,S12000033,Dyce - 02,Dyce,Aberdeen City,NaN,11584.0
AB21 7LE,23,57.211763,-2.182487,AB217LE,AB21 7LE,199606.0,0.0,0.0,S00090884,S01006750,S02001278,S12000033,Dyce - 02,Dyce,Aberdeen City,NaN,11586.0
AB21 7LF,24,57.203430,-2.173906,AB217LF,AB21 7LF,199606.0,0.0,0.0,S00090258,S01006754,S02001278,S12000033,Dyce - 06,Dyce,Aberdeen City,NaN,11588.0
AB21 7LG,25,57.210955,-2.181887,AB217LG,AB21 7LG,199606.0,0.0,0.0,S00090284,S01006750,S02001278,S12000033,Dyce - 02,Dyce,Aberdeen City,NaN,11590.0
AB21 7LH,26,57.210265,-2.180907,AB217LH,AB21 7LH,199606.0,0.0,0.0,S00090284,S01006750,S02001278,S12000033,Dyce - 02,Dyce,Aberdeen City,NaN,11591.0
AB21 7LJ,27,57.210353,-2.181967,AB217LJ,AB21 7LJ,199606.0,0.0,0.0,S00090284,S01006750,S02001278,S12000033,Dyce - 02,Dyce,Aberdeen City,NaN,11592.0
AB21 7LL,28,57.212460,-2.184957,AB217LL,AB21 7LL,199606.0,0.0,0.0,S00090887,S01006750,S02001278,S12000033,Dyce - 02,Dyce,Aberdeen City,NaN,11593.0
AB21 7LN,29,57.210324,-2.183374,AB217LN,AB21 7LN,199606.0,0.0,0.0,S00090881,S01006752,S02001278,S12000033,Dyce - 04,Dyce,Aberdeen City,NaN,11594.0
AB21 7LP,30,57.209903,-2.182892,AB217LP,AB21 7LP,199606.0,0.0,0.0,S00090881,S01006752,S02001278,S12000033,Dyce - 04,Dyce,Aberdeen City,NaN,11595.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
YO41 1FF,2637739,53.994048,-0.907929,YO411FF,YO41 1FF,201805.0,0.0,0.0,E00066241,E01013126,E02002692,E06000011,East Riding of Yorkshire 009E,East Riding of Yorkshire 009,East Riding of Yorkshire,NaN,2606950.0
YO41 1FH,2637740,53.994536,-0.907153,YO411FH,YO41 1FH,201806.0,0.0,0.0,E00066241,E01013126,E02002692,E06000011,East Riding of Yorkshire 009E,East Riding of Yorkshire 009,East Riding of Yorkshire,NaN,2606960.0
YO41 1FP,2637741,53.994274,-0.906047,YO411FP,YO41 1FP,201806.0,0.0,0.0,E00066241,E01013126,E02002692,E06000011,East Riding of Yorkshire 009E,East Riding of Yorkshire 009,East Riding of Yorkshire,NaN,2607007.0
YO41 1SD,2637742,53.993068,-0.902921,YO411SD,YO41 1SD,201806.0,0.0,0.0,E00065894,E01013060,E02002692,E06000011,East Riding of Yorkshire 009C,East Riding of Yorkshire 009,East Riding of Yorkshire,NaN,2606861.0
YO41 1SP,2637743,53.993923,-0.903020,YO411SP,YO41 1SP,201806.0,0.0,0.0,E00065894,E01013060,E02002692,E06000011,East Riding of Yorkshire 009C,East Riding of Yorkshire 009,East Riding of Yorkshire,NaN,2606943.0
YO41 4EN,2637744,53.921331,-0.933459,YO414EN,YO41 4EN,201805.0,0.0,0.0,E00067907,E01013451,E02002791,E06000014,York 020C,York 020,York,NaN,2607274.0
YO42 1AF,2637745,53.926341,-0.766861,YO421AF,YO42 1AF,201805.0,0.0,0.0,E00065887,E01013052,E02002694,E06000011,East Riding of Yorkshire 011A,East Riding of Yorkshire 011,East Riding of Yorkshire,NaN,2607577.0
YO42 1AG,2637746,53.926160,-0.767597,YO421AG,YO42 1AG,201805.0,0.0,0.0,E00065887,E01013052,E02002694,E06000011,East Riding of Yorkshire 011A,East Riding of Yorkshire 011,East Riding of Yorkshire,NaN,2607578.0
YO42 2FY,2637747,53.920843,-0.776814,YO422FY,YO42 2FY,201805.0,0.0,0.0,E00065887,E01013052,E02002694,E06000011,East Riding of Yorkshire 011A,East Riding of Yorkshire 011,East Riding of Yorkshire,NaN,2607871.0
YO42 2FZ,2637748,53.921301,-0.775856,YO422FZ,YO42 2FZ,201806.0,0.0,0.0,E00065887,E01013052,E02002694,E06000011,East Riding of Yorkshire 011A,East Riding of Yorkshire 011,East Riding of Yorkshire,NaN,2607872.0
YO42 2SD,2637749,53.936403,-0.786672,YO422SD,YO42 2SD,201805.0,0.0,0.0,E00065869,E01013053,E02002694,E06000011,East Riding of Yorkshire 011B,East Riding of Yorkshire 011,East Riding of Yorkshire,NaN,2607929.0
YO42 2SF,2637750,53.937002,-0.788117,YO422SF,YO42 2SF,201807.0,0.0,0.0,E00065869,E01013053,E02002694,E06000011,East Riding of Yorkshire 011B,East Riding of Yorkshire 011,East Riding of Yorkshire,NaN,2607931.0
YO42 2SJ,2637751,53.931148,-0.781661,YO422SJ,YO42 2SJ,201806.0,0.0,0.0,E00065882,E01013054,E02002694,E06000011,East Riding of Yorkshire 011C,East Riding of Yorkshire 011,East Riding of Yorkshire,NaN,2607933.0
YO43 3GR,2637752,53.863052,-0.681209,YO433GR,YO43 3GR,201805.0,0.0,0.0,E00066214,E01013123,E02002698,E06000011,East Riding of Yorkshire 015C,East Riding of Yorkshire 015,East Riding of Yorkshire,NaN,2608385.0
YO43 3GS,2637753,53.863193,-0.681767,YO433GS,YO43 3GS,201805.0,0.0,0.0,E00066214,E01013123,E02002698,E06000011,East Riding of Yorkshire 015C,East Riding of Yorkshire 015,East Riding of Yorkshire,NaN,2608386.0
YO43 3GT,2637754,53.862755,-0.680321,YO433GT,YO43 3GT,201805.0,0.0,0.0,E00066227,E01013123,E02002698,E06000011,East Riding of Yorkshire 015C,East Riding of Yorkshire 015,East Riding of Yorkshire,NaN,2608387.0
YO61 1AD,2637755,54.101931,-1.106358,YO611AD,YO61 1AD,201806.0,0.0,0.0,E00140659,E01027622,E02005759,E07000164,Hambleton 010E,Hambleton 010,Hambleton,NaN,2611275.0
YO61 3GR,2637756,54.118745,-1.192636,YO613GR,YO61 3GR,201805.0,0.0,0.0,E00140499,E01027594,E02005759,E07000164,Hambleton 010A,Hambleton 010,Hambleton,NaN,2611752.0
YO7 3SL,2637757,54.220258,-1.356920,YO7 3SL,YO7 3SL,201807.0,0.0,0.0,E00140648,E01027621,E02005758,E07000164,Hambleton 009A,Hambleton 009,Hambleton,NaN,2613481.0
YO7 4ED,2637758,54.244951,-1.408635,YO7 4ED,YO7 4ED,201805.0,0.0,0.0,E00140715,E01027633,E02005756,E07000164,Hambleton 007C,Hambleton 007,Hambleton,NaN,2613649.0
YO8 1DT,2637759,53.784954,-1.067704,YO8 1DT,YO8 1DT,201805.0,0.0,1.0,E00170114,E01027909,E02005813,E07000169,Selby 005E,Selby 005,Selby,NaN,2614050.0
YO8 3NG,2637760,53.787162,-1.069629,YO8 3NG,YO8 3NG,201806.0,0.0,0.0,E00142186,E01027905,E02005813,E07000169,Selby 005B,Selby 005,Selby,NaN,2614722.0
YO8 4FB,2637761,53.782466,-1.074893,YO8 4FB,YO8 4FB,201807.0,0.0,0.0,E00142217,E01027911,E02005814,E07000169,Selby 006C,Selby 006,Selby,NaN,2614581.0
YO8 5BZ,2637762,53.790220,-1.044621,YO8 5BZ,YO8 5BZ,201807.0,0.0,1.0,E00142030,E01027878,E02005813,E07000169,Selby 005A,Selby 005,Selby,NaN,2615124.0
YO8 8GF,2637763,53.772379,-1.051611,YO8 8GF,YO8 8GF,201806.0,0.0,0.0,E00170110,E01027910,E02005813,E07000169,Selby 005F,Selby 005,Selby,NaN,2615511.0
YO8 9SH,2637764,53.767041,-1.099611,YO8 9SH,YO8 9SH,201806.0,0.0,0.0,E00142044,E01027881,E02005814,E07000169,Selby 006A,Selby 006,Selby,NaN,2615934.0
YO8 9UB,2637765,53.768634,-1.101064,YO8 9UB,YO8 9UB,201805.0,0.0,0.0,E00142039,E01027881,E02005814,E07000169,Selby 006A,Selby 006,Selby,NaN,2616037.0
ZE2 9FL,2637766,60.278584,-1.247098,ZE2 9FL,ZE2 9FL,201805.0,0.0,0.0,S00128975,S01012407,S02002326,S12000027,East and West Mainland - 02,East and West Mainland,Shetland Islands,NaN,2616710.0
ZE2 9FP,2637767,60.128408,-1.208825,ZE2 9FP,ZE2 9FP,201806.0,0.0,0.0,S00129099,S01012391,S02002323,S12000027,Lerwick South - 01,Lerwick South,Shetland Islands,NaN,2616711.0
ZE2 9FQ,2637768,60.128408,-1.208825,ZE2 9FQ,ZE2 9FQ,201807.0,0.0,0.0,S00129099,S01012391,S02002323,S12000027,Lerwick South - 01,Lerwick South,Shetland Islands,NaN,2616712.0

In [26]:
joined = joined.drop(['id','pcd7', 'pcd8', 'dointr',
       'doterm', 'usertype','ladnmw'],axis=1)

In [29]:
joined.to_csv('Postcode_coordinates.csv',index=True)

In [27]:
joined.head(3)

,latitude,longitude,oa11cd,lsoa11cd,msoa11cd,ladcd,lsoa11nm,msoa11nm,ladnm,FID
postcode,,,,,,,,,,
AB10 1XG,57.144165,-2.114848,S00088970,S01006571,S02001247,S12000033,West End North - 01,West End North,Aberdeen City,3015.0
AB10 6RN,57.137880,-2.121487,S00089205,S01006576,S02001248,S12000033,West End South - 02,West End South,Aberdeen City,3146.0
AB10 7JB,57.124274,-2.127190,S00089357,S01006530,S02001239,S12000033,Garthdee - 05,Garthdee,Aberdeen City,3489.0

In [40]:
joined.isnull().sum().sum()

24564

In [30]:
joined.shape

(1765734, 10)

In [39]:
joined.isnull().any().any()

True

In [41]:
joined.dropna()

,latitude,longitude,oa11cd,lsoa11cd,msoa11cd,ladcd,lsoa11nm,msoa11nm,ladnm,FID
postcode,,,,,,,,,,
AB10 1XG,57.144165,-2.114848,S00088970,S01006571,S02001247,S12000033,West End North - 01,West End North,Aberdeen City,3015.0
AB10 6RN,57.137880,-2.121487,S00089205,S01006576,S02001248,S12000033,West End South - 02,West End South,Aberdeen City,3146.0
AB10 7JB,57.124274,-2.127190,S00089357,S01006530,S02001239,S12000033,Garthdee - 05,Garthdee,Aberdeen City,3489.0
AB11 5QN,57.142701,-2.093295,S00090582,S01006587,S02001250,S12000033,City Centre East - 01,City Centre East,Aberdeen City,3876.0
AB11 6UL,57.137547,-2.112233,S00090560,S01006597,S02001251,S12000033,Ferryhill North - 07,Ferryhill North,Aberdeen City,3834.0
AB11 8RQ,57.135978,-2.072115,S00089114,S01006631,S02001258,S12000033,Torry East - 01,Torry East,Aberdeen City,4068.0
AB12 3FJ,57.098003,-2.077438,S00090233,S01006619,S02001256,S12000033,Cove North - 01,Cove North,Aberdeen City,4536.0
AB12 4NA,57.064273,-2.130018,S00092225,S01006851,S02001295,S12000034,Banchory-Devenick and Findon - 04,Banchory-Devenick and Findon,Aberdeenshire,5068.0
AB12 5GL,57.081938,-2.246567,S00091322,S01006853,S02001296,S12000034,"Dunecht, Durris and Drumoak - 01","Dunecht, Durris and Drumoak",Aberdeenshire,5189.0
AB12 9SP,57.148707,-2.097806,S00090540,S01006646,S02001261,S12000033,George Street - 02,George Street,Aberdeen City,5214.0
AB14 0TQ,57.101557,-2.268486,S00090294,S01006507,S02001236,S12000033,Culter - 02,Culter,Aberdeen City,5611.0
AB15 5HB,57.147428,-2.147266,S00089703,S01006572,S02001247,S12000033,West End North - 02,West End North,Aberdeen City,5895.0
AB15 6NA,57.151797,-2.185398,S00088959,S01006737,S02001275,S12000033,Kingswells - 06,Kingswells,Aberdeen City,6387.0
AB15 8BA,57.135624,-2.175239,S00089394,S01006551,S02001243,S12000033,Hazlehead - 05,Hazlehead,Aberdeen City,6487.0
AB15 8UF,57.154006,-2.224402,S00090946,S01006735,S02001275,S12000033,Kingswells - 04,Kingswells,Aberdeen City,6768.0
AB15 9SE,57.118648,-2.174251,S00089428,S01006523,S02001238,S12000033,"Cults, Bieldside and Milltimber East - 06","Cults, Bieldside and Milltimber Eas",Aberdeen City,7087.0
AB16 5ST,57.163466,-2.159333,S00089845,S01006722,S02001273,S12000033,Northfield - 04,Northfield,Aberdeen City,7172.0
AB16 6SZ,57.158751,-2.165215,S00089990,S01006713,S02001271,S12000033,Sheddocksley - 06,Sheddocksley,Aberdeen City,7330.0
AB16 7NX,57.168438,-2.161636,S00090028,S01006724,S02001273,S12000033,Northfield - 06,Northfield,Aberdeen City,7414.0
AB21 0AL,57.263420,-2.158605,S00091112,S01006950,S02001311,S12000034,Newmachar and Fintray - 05,Newmachar and Fintray,Aberdeenshire,11018.0
AB21 0TF,57.221883,-2.273318,S00088967,S01006755,S02001278,S12000033,Dyce - 07,Dyce,Aberdeen City,11117.0
AB21 7LD,57.212136,-2.185602,S00090886,S01006750,S02001278,S12000033,Dyce - 02,Dyce,Aberdeen City,11584.0
AB21 7LE,57.211763,-2.182487,S00090884,S01006750,S02001278,S12000033,Dyce - 02,Dyce,Aberdeen City,11586.0
AB21 7LF,57.203430,-2.173906,S00090258,S01006754,S02001278,S12000033,Dyce - 06,Dyce,Aberdeen City,11588.0
AB21 7LG,57.210955,-2.181887,S00090284,S01006750,S02001278,S12000033,Dyce - 02,Dyce,Aberdeen City,11590.0
AB21 7LH,57.210265,-2.180907,S00090284,S01006750,S02001278,S12000033,Dyce - 02,Dyce,Aberdeen City,11591.0
AB21 7LJ,57.210353,-2.181967,S00090284,S01006750,S02001278,S12000033,Dyce - 02,Dyce,Aberdeen City,11592.0
AB21 7LL,57.212460,-2.184957,S00090887,S01006750,S02001278,S12000033,Dyce - 02,Dyce,Aberdeen City,11593.0
AB21 7LN,57.210324,-2.183374,S00090881,S01006752,S02001278,S12000033,Dyce - 04,Dyce,Aberdeen City,11594.0
AB21 7LP,57.209903,-2.182892,S00090881,S01006752,S02001278,S12000033,Dyce - 04,Dyce,Aberdeen City,11595.0
...,...,...,...,...,...,...,...,...,...,...
YO41 1FF,53.994048,-0.907929,E00066241,E01013126,E02002692,E06000011,East Riding of Yorkshire 009E,East Riding of Yorkshire 009,East Riding of Yorkshire,2606950.0
YO41 1FH,53.994536,-0.907153,E00066241,E01013126,E02002692,E06000011,East Riding of Yorkshire 009E,East Riding of Yorkshire 009,East Riding of Yorkshire,2606960.0
YO41 1FP,53.994274,-0.906047,E00066241,E01013126,E02002692,E06000011,East Riding of Yorkshire 009E,East Riding of Yorkshire 009,East Riding of Yorkshire,2607007.0
YO41 1SD,53.993068,-0.902921,E00065894,E01013060,E02002692,E06000011,East Riding of Yorkshire 009C,East Riding of Yorkshire 009,East Riding of Yorkshire,2606861.0
YO41 1SP,53.993923,-0.903020,E00065894,E01013060,E02002692,E06000011,East Riding of Yorkshire 009C,East Riding of Yorkshire 009,East Riding of Yorkshire,2606943.0
YO41 4EN,53.921331,-0.933459,E00067907,E01013451,E02002791,E06000014,York 020C,York 020,York,2607274.0
YO42 1AF,53.926341,-0.766861,E00065887,E01013052,E02002694,E06000011,East Riding of Yorkshire 011A,East Riding of Yorkshire 011,East Riding of Yorkshire,2607577.0
YO42 1AG,53.926160,-0.767597,E00065887,E01013052,E02002694,E06000011,East Riding of Yorkshire 011A,East Riding of Yorkshire 011,East Riding of Yorkshire,2607578.0
YO42 2FY,53.920843,-0.776814,E00065887,E01013052,E02002694,E06000011,East Riding of Yorkshire 011A,East Riding of Yorkshire 011,East Riding of Yorkshire,2607871.0
YO42 2FZ,53.921301,-0.775856,E00065887,E01013052,E02002694,E06000011,East Riding of Yorkshire 011A,East Riding of Yorkshire 011,East Riding of Yorkshire,2607872.0
YO42 2SD,53.936403,-0.786672,E00065869,E01013053,E02002694,E06000011,East Riding of Yorkshire 011B,East Riding of Yorkshire 011,East Riding of Yorkshire,2607929.0
YO42 2SF,53.937002,-0.788117,E00065869,E01013053,E02002694,E06000011,East Riding of Yorkshire 011B,East Riding of Yorkshire 011,East Riding of Yorkshire,2607931.0
YO42 2SJ,53.931148,-0.781661,E00065882,E01013054,E02002694,E06000011,East Riding of Yorkshire 011C,East Riding of Yorkshire 011,East Riding of Yorkshire,2607933.0
YO43 3GR,53.863052,-0.681209,E00066214,E01013123,E02002698,E06000011,East Riding of Yorkshire 015C,East Riding of Yorkshire 015,East Riding of Yorkshire,2608385.0
YO43 3GS,53.863193,-0.681767,E00066214,E01013123,E02002698,E06000011,East Riding of Yorkshire 015C,East Riding of Yorkshire 015,East Riding of Yorkshire,2608386.0
YO43 3GT,53.862755,-0.680321,E00066227,E01013123,E02002698,E06000011,East Riding of Yorkshire 015C,East Riding of Yorkshire 015,East Riding of Yorkshire,2608387.0
YO61 1AD,54.101931,-1.106358,E00140659,E01027622,E02005759,E07000164,Hambleton 010E,Hambleton 010,Hambleton,2611275.0
YO61 3GR,54.118745,-1.192636,E00140499,E01027594,E02005759,E07000164,Hambleton 010A,Hambleton 010,Hambleton,2611752.0
YO7 3SL,54.220258,-1.356920,E00140648,E01027621,E02005758,E07000164,Hambleton 009A,Hambleton 009,Hambleton,2613481.0
YO7 4ED,54.244951,-1.408635,E00140715,E01027633,E02005756,E07000164,Hambleton 007C,Hambleton 007,Hambleton,2613649.0
YO8 1DT,53.784954,-1.067704,E00170114,E01027909,E02005813,E07000169,Selby 005E,Selby 005,Selby,2614050.0
YO8 3NG,53.787162,-1.069629,E00142186,E01027905,E02005813,E07000169,Selby 005B,Selby 005,Selby,2614722.0
YO8 4FB,53.782466,-1.074893,E00142217,E01027911,E02005814,E07000169,Selby 006C,Selby 006,Selby,2614581.0
YO8 5BZ,53.790220,-1.044621,E00142030,E01027878,E02005813,E07000169,Selby 005A,Selby 005,Selby,2615124.0
YO8 8GF,53.772379,-1.051611,E00170110,E01027910,E02005813,E07000169,Selby 005F,Selby 005,Selby,2615511.0
YO8 9SH,53.767041,-1.099611,E00142044,E01027881,E02005814,E07000169,Selby 006A,Selby 006,Selby,2615934.0
YO8 9UB,53.768634,-1.101064,E00142039,E01027881,E02005814,E07000169,Selby 006A,Selby 006,Selby,2616037.0
ZE2 9FL,60.278584,-1.247098,S00128975,S01012407,S02002326,S12000027,East and West Mainland - 02,East and West Mainland,Shetland Islands,2616710.0
ZE2 9FP,60.128408,-1.208825,S00129099,S01012391,S02002323,S12000027,Lerwick South - 01,Lerwick South,Shetland Islands,2616711.0
ZE2 9FQ,60.128408,-1.208825,S00129099,S01012391,S02002323,S12000027,Lerwick South - 01,Lerwick South,Shetland Islands,2616712.0

In [43]:
joined.shape

(1765734, 10)

In [32]:
nan_rows = joined[joined['msoa11cd'].isnull()]

In [44]:
nan_lad_rows = joined[joined['ladcd'].isnull()]

In [45]:
nan_lad_rows

,latitude,longitude,oa11cd,lsoa11cd,msoa11cd,ladcd,lsoa11nm,msoa11nm,ladnm,FID
postcode,,,,,,,,,,
IV51 0AE,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1105584.0
BN91 9AA,50.923170,-0.346777,NaN,NaN,NaN,NaN,NaN,NaN,NaN,241647.0
BD98 1GA,53.983502,-2.013688,NaN,NaN,NaN,NaN,NaN,NaN,NaN,171673.0
BD98 1GB,54.052625,-2.051348,NaN,NaN,NaN,NaN,NaN,NaN,NaN,171678.0
BD98 1GD,53.752752,-1.778608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,171679.0
BD98 1GG,53.880912,-2.057586,NaN,NaN,NaN,NaN,NaN,NaN,NaN,171685.0
BD98 1YA,54.086296,-2.101362,NaN,NaN,NaN,NaN,NaN,NaN,NaN,171689.0
BD98 1YB,54.007521,-1.888642,NaN,NaN,NaN,NaN,NaN,NaN,NaN,171694.0
BD98 1YD,53.876774,-1.907758,NaN,NaN,NaN,NaN,NaN,NaN,NaN,171699.0
BD98 1YY,54.199320,-2.290625,NaN,NaN,NaN,NaN,NaN,NaN,NaN,171704.0
BD98 5GA,54.003071,-1.958101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,171709.0
BD98 5GG,54.101570,-1.971505,NaN,NaN,NaN,NaN,NaN,NaN,NaN,171714.0
BD98 5YA,53.888645,-2.067349,NaN,NaN,NaN,NaN,NaN,NaN,NaN,171716.0
BD98 5YY,53.946593,-2.110514,NaN,NaN,NaN,NaN,NaN,NaN,NaN,171721.0
KW1 1DL,58.515336,-3.241584,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OX29 0YH,51.794597,-1.546574,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
WR2 5SF,52.190878,-2.243496,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
YO32 2RS,54.022938,-1.058986,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SA18 3FG,51.795291,-3.948701,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
KA8 3SX,55.469814,-4.610165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RH6 4RP,51.188429,-0.162581,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BA1 4JX,51.403872,-2.397502,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SS2 5TZ,51.557572,0.708540,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LN11 4YL,53.347522,0.001774,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CW4 4SN,53.208429,-2.319504,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PR2 5BR,53.782462,-2.693439,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DA15 5ET,51.441422,0.101025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
EH22 4TA,55.870090,-3.058825,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OL1 1GQ,53.557604,-2.113629,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SS3 8QT,51.564620,0.831471,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
BT63 5ZU,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,343432.0
BT66 6FE,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,343927.0
BT7 3LZ,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,346250.0
BT74 0BN,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,347732.0
BT74 0BP,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,347739.0
BT74 4GX,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,348008.0
BT78 1FB,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,349266.0
BT92 8YZ,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,356458.0
BT94 4QZ,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,358602.0
N1P 3EE,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1463077.0
N1P 3EF,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1463080.0
N1P 3EG,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1463083.0
N1P 3EH,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1463086.0
N1P 3EJ,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1463089.0
N1P 3EL,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1463092.0
N1P 3EN,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1463095.0
N1P 3EP,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1463098.0
N1P 3EQ,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1463101.0
SE1P 6ED,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2029341.0
SE1P 6EE,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2029345.0
SE1P 6EF,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2029388.0
SE1P 6EG,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2029391.0
SE1P 6EH,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2029394.0
SE1P 6EJ,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2029397.0
SE1P 6EL,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2029400.0
SE1P 6EN,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2029403.0
SE1P 6EP,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2029406.0
SE1P 6EQ,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2029409.0
SE1P 6ER,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2029412.0
WV98 2EG,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2581940.0

In [33]:
nan_rows

,latitude,longitude,oa11cd,lsoa11cd,msoa11cd,ladcd,lsoa11nm,msoa11nm,ladnm,FID
postcode,,,,,,,,,,
IV51 0AE,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1105584.0
BN91 9AA,50.923170,-0.346777,NaN,NaN,NaN,NaN,NaN,NaN,NaN,241647.0
BD98 1GA,53.983502,-2.013688,NaN,NaN,NaN,NaN,NaN,NaN,NaN,171673.0
BD98 1GB,54.052625,-2.051348,NaN,NaN,NaN,NaN,NaN,NaN,NaN,171678.0
BD98 1GD,53.752752,-1.778608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,171679.0
BD98 1GG,53.880912,-2.057586,NaN,NaN,NaN,NaN,NaN,NaN,NaN,171685.0
BD98 1YA,54.086296,-2.101362,NaN,NaN,NaN,NaN,NaN,NaN,NaN,171689.0
BD98 1YB,54.007521,-1.888642,NaN,NaN,NaN,NaN,NaN,NaN,NaN,171694.0
BD98 1YD,53.876774,-1.907758,NaN,NaN,NaN,NaN,NaN,NaN,NaN,171699.0
BD98 1YY,54.199320,-2.290625,NaN,NaN,NaN,NaN,NaN,NaN,NaN,171704.0
BD98 5GA,54.003071,-1.958101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,171709.0
BD98 5GG,54.101570,-1.971505,NaN,NaN,NaN,NaN,NaN,NaN,NaN,171714.0
BD98 5YA,53.888645,-2.067349,NaN,NaN,NaN,NaN,NaN,NaN,NaN,171716.0
BD98 5YY,53.946593,-2.110514,NaN,NaN,NaN,NaN,NaN,NaN,NaN,171721.0
KW1 1DL,58.515336,-3.241584,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OX29 0YH,51.794597,-1.546574,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
WR2 5SF,52.190878,-2.243496,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
YO32 2RS,54.022938,-1.058986,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SA18 3FG,51.795291,-3.948701,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
KA8 3SX,55.469814,-4.610165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RH6 4RP,51.188429,-0.162581,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BA1 4JX,51.403872,-2.397502,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SS2 5TZ,51.557572,0.708540,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LN11 4YL,53.347522,0.001774,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CW4 4SN,53.208429,-2.319504,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PR2 5BR,53.782462,-2.693439,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DA15 5ET,51.441422,0.101025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
EH22 4TA,55.870090,-3.058825,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OL1 1GQ,53.557604,-2.113629,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SS3 8QT,51.564620,0.831471,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
BT63 5ZU,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,343432.0
BT66 6FE,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,343927.0
BT7 3LZ,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,346250.0
BT74 0BN,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,347732.0
BT74 0BP,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,347739.0
BT74 4GX,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,348008.0
BT78 1FB,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,349266.0
BT92 8YZ,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,356458.0
BT94 4QZ,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,358602.0
N1P 3EE,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1463077.0
N1P 3EF,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1463080.0
N1P 3EG,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1463083.0
N1P 3EH,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1463086.0
N1P 3EJ,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1463089.0
N1P 3EL,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1463092.0
N1P 3EN,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1463095.0
N1P 3EP,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1463098.0
N1P 3EQ,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1463101.0
SE1P 6ED,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2029341.0
SE1P 6EE,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2029345.0
SE1P 6EF,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2029388.0
SE1P 6EG,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2029391.0
SE1P 6EH,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2029394.0
SE1P 6EJ,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2029397.0
SE1P 6EL,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2029400.0
SE1P 6EN,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2029403.0
SE1P 6EP,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2029406.0
SE1P 6EQ,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2029409.0
SE1P 6ER,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2029412.0
WV98 2EG,99.999999,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2581940.0

In [46]:
joined.isna()

,latitude,longitude,oa11cd,lsoa11cd,msoa11cd,ladcd,lsoa11nm,msoa11nm,ladnm,FID
postcode,,,,,,,,,,
AB10 1XG,False,False,False,False,False,False,False,False,False,False
AB10 6RN,False,False,False,False,False,False,False,False,False,False
AB10 7JB,False,False,False,False,False,False,False,False,False,False
AB11 5QN,False,False,False,False,False,False,False,False,False,False
AB11 6UL,False,False,False,False,False,False,False,False,False,False
AB11 8RQ,False,False,False,False,False,False,False,False,False,False
AB12 3FJ,False,False,False,False,False,False,False,False,False,False
AB12 4NA,False,False,False,False,False,False,False,False,False,False
AB12 5GL,False,False,False,False,False,False,False,False,False,False
AB12 9SP,False,False,False,False,False,False,False,False,False,False
AB14 0TQ,False,False,False,False,False,False,False,False,False,False
AB15 5HB,False,False,False,False,False,False,False,False,False,False
AB15 6NA,False,False,False,False,False,False,False,False,False,False
AB15 8BA,False,False,False,False,False,False,False,False,False,False
AB15 8UF,False,False,False,False,False,False,False,False,False,False
AB15 9SE,False,False,False,False,False,False,False,False,False,False
AB16 5ST,False,False,False,False,False,False,False,False,False,False
AB16 6SZ,False,False,False,False,False,False,False,False,False,False
AB16 7NX,False,False,False,False,False,False,False,False,False,False
AB21 0AL,False,False,False,False,False,False,False,False,False,False
AB21 0TF,False,False,False,False,False,False,False,False,False,False
AB21 7LD,False,False,False,False,False,False,False,False,False,False
AB21 7LE,False,False,False,False,False,False,False,False,False,False
AB21 7LF,False,False,False,False,False,False,False,False,False,False
AB21 7LG,False,False,False,False,False,False,False,False,False,False
AB21 7LH,False,False,False,False,False,False,False,False,False,False
AB21 7LJ,False,False,False,False,False,False,False,False,False,False
AB21 7LL,False,False,False,False,False,False,False,False,False,False
AB21 7LN,False,False,False,False,False,False,False,False,False,False
AB21 7LP,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
YO41 1FF,False,False,False,False,False,False,False,False,False,False
YO41 1FH,False,False,False,False,False,False,False,False,False,False
YO41 1FP,False,False,False,False,False,False,False,False,False,False
YO41 1SD,False,False,False,False,False,False,False,False,False,False
YO41 1SP,False,False,False,False,False,False,False,False,False,False
YO41 4EN,False,False,False,False,False,False,False,False,False,False
YO42 1AF,False,False,False,False,False,False,False,False,False,False
YO42 1AG,False,False,False,False,False,False,False,False,False,False
YO42 2FY,False,False,False,False,False,False,False,False,False,False
YO42 2FZ,False,False,False,False,False,False,False,False,False,False
YO42 2SD,False,False,False,False,False,False,False,False,False,False
YO42 2SF,False,False,False,False,False,False,False,False,False,False
YO42 2SJ,False,False,False,False,False,False,False,False,False,False
YO43 3GR,False,False,False,False,False,False,False,False,False,False
YO43 3GS,False,False,False,False,False,False,False,False,False,False
YO43 3GT,False,False,False,False,False,False,False,False,False,False
YO61 1AD,False,False,False,False,False,False,False,False,False,False
YO61 3GR,False,False,False,False,False,False,False,False,False,False
YO7 3SL,False,False,False,False,False,False,False,False,False,False
YO7 4ED,False,False,False,False,False,False,False,False,False,False
YO8 1DT,False,False,False,False,False,False,False,False,False,False
YO8 3NG,False,False,False,False,False,False,False,False,False,False
YO8 4FB,False,False,False,False,False,False,False,False,False,False
YO8 5BZ,False,False,False,False,False,False,False,False,False,False
YO8 8GF,False,False,False,False,False,False,False,False,False,False
YO8 9SH,False,False,False,False,False,False,False,False,False,False
YO8 9UB,False,False,False,False,False,False,False,False,False,False
ZE2 9FL,False,False,False,False,False,False,False,False,False,False
ZE2 9FP,False,False,False,False,False,False,False,False,False,False
ZE2 9FQ,False,False,False,False,False,False,False,False,False,False

In [68]:
finaljoined = joined.dropna()

In [69]:
finaljoined.shape

(1749015, 10)

In [70]:
finaljoined.to_csv('Postcode_coordinates.csv',index=True)

In [50]:
population = pd.read_csv('/Users/jyothigupta/Documents/UCL/CASA_Dissertations/UrbanScalinglaw/Data/population/population.csv',na_values='')

In [51]:
population.head(2)

,Area code,population,Males,Females,Lives in a household,Lives in a communal establishment,Schoolchild,Area,Density
0,W92000004,3063456.0,1504228.0,1559228.0,3011182.0,52274.0,35061.0,2073511.0,1.5
1,W92000004,3063456.0,1504228.0,1559228.0,3011182.0,52274.0,35061.0,2073511.0,1.5

In [52]:
population.shape

(464, 9)

In [53]:
population= population.set_index('Area code')
population.head(4)

,population,Males,Females,Lives in a household,Lives in a communal establishment,Schoolchild,Area,Density
Area code,,,,,,,,
W92000004,3063456.0,1504228.0,1559228.0,3011182.0,52274.0,35061.0,2073511.0,1.5
W92000004,3063456.0,1504228.0,1559228.0,3011182.0,52274.0,35061.0,2073511.0,1.5
W06000024,58802.0,28791.0,30011.0,58334.0,468.0,474.0,11139.0,5.3
W06000023,132976.0,65683.0,67293.0,131047.0,1929.0,2117.0,518037.0,0.3

In [54]:
population.dtypes

population                           float64
Males                                float64
Females                              float64
Lives in a household                 float64
Lives in a communal establishment    float64
Schoolchild                          float64
Area                                 float64
Density                              float64
dtype: object

In [57]:
population.isna()

,population,Males,Females,Lives in a household,Lives in a communal establishment,Schoolchild,Area,Density
Area code,,,,,,,,
W92000004,False,False,False,False,False,False,False,False
W92000004,False,False,False,False,False,False,False,False
W06000024,False,False,False,False,False,False,False,False
W06000023,False,False,False,False,False,False,False,False
W06000022,False,False,False,False,False,False,False,False
W06000021,False,False,False,False,False,False,False,False
W06000020,False,False,False,False,False,False,False,False
W06000019,False,False,False,False,False,False,False,False
W06000018,False,False,False,False,False,False,False,False
W06000016,False,False,False,False,False,False,False,False
W06000015,False,False,False,False,False,False,False,False
W06000014,False,False,False,False,False,False,False,False
W06000013,False,False,False,False,False,False,False,False
W06000012,False,False,False,False,False,False,False,False
W06000011,False,False,False,False,False,False,False,False
W06000010,False,False,False,False,False,False,False,False
W06000009,False,False,False,False,False,False,False,False
W06000008,False,False,False,False,False,False,False,False
W06000006,False,False,False,False,False,False,False,False
W06000005,False,False,False,False,False,False,False,False
W06000004,False,False,False,False,False,False,False,False
W06000003,False,False,False,False,False,False,False,False
W06000002,False,False,False,False,False,False,False,False
W06000001,False,False,False,False,False,False,False,False
S92000003,False,False,False,False,False,False,False,False
S92000003,False,False,False,False,False,False,False,False
S12000046,False,False,False,False,False,False,False,False
S12000045,False,False,False,False,False,False,False,False
S12000044,False,False,False,False,False,False,False,False
S12000042,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
E06000001,False,False,False,False,False,False,False,False
95Z,False,False,False,False,False,False,False,False
95Y,False,False,False,False,False,False,False,False
95X,False,False,False,False,False,False,False,False
95W,False,False,False,False,False,False,False,False
95V,False,False,False,False,False,False,False,False
95U,False,False,False,False,False,False,False,False
95T,False,False,False,False,False,False,False,False
95S,False,False,False,False,False,False,False,False
95R,False,False,False,False,False,False,False,False
95Q,False,False,False,False,False,False,False,False
95P,False,False,False,False,False,False,False,False
95O,False,False,False,False,False,False,False,False
95N,False,False,False,False,False,False,False,False
95M,False,False,False,False,False,False,False,False
95L,False,False,False,False,False,False,False,False
95K,False,False,False,False,False,False,False,False
95J,False,False,False,False,False,False,False,False
95I,False,False,False,False,False,False,False,False
95H,False,False,False,False,False,False,False,False
95G,False,False,False,False,False,False,False,False
95F,False,False,False,False,False,False,False,False
95E,False,False,False,False,False,False,False,False
95D,False,False,False,False,False,False,False,False
95C,False,False,False,False,False,False,False,False
95B,False,False,False,False,False,False,False,False
95A,False,False,False,False,False,False,False,False
NaN,True,True,True,True,True,True,True,True
"Source: Office for National Statistics, Northern Ireland Statistics and Research Agency,",True,True,True,True,True,True,True,True
National Records of Scotland © Crown Copyright 2013,True,True,True,True,True,True,True,True

In [62]:
pop = population.dropna()

In [63]:
pop.isna()

,population,Males,Females,Lives in a household,Lives in a communal establishment,Schoolchild,Area,Density
Area code,,,,,,,,
W92000004,False,False,False,False,False,False,False,False
W92000004,False,False,False,False,False,False,False,False
W06000024,False,False,False,False,False,False,False,False
W06000023,False,False,False,False,False,False,False,False
W06000022,False,False,False,False,False,False,False,False
W06000021,False,False,False,False,False,False,False,False
W06000020,False,False,False,False,False,False,False,False
W06000019,False,False,False,False,False,False,False,False
W06000018,False,False,False,False,False,False,False,False
W06000016,False,False,False,False,False,False,False,False
W06000015,False,False,False,False,False,False,False,False
W06000014,False,False,False,False,False,False,False,False
W06000013,False,False,False,False,False,False,False,False
W06000012,False,False,False,False,False,False,False,False
W06000011,False,False,False,False,False,False,False,False
W06000010,False,False,False,False,False,False,False,False
W06000009,False,False,False,False,False,False,False,False
W06000008,False,False,False,False,False,False,False,False
W06000006,False,False,False,False,False,False,False,False
W06000005,False,False,False,False,False,False,False,False
W06000004,False,False,False,False,False,False,False,False
W06000003,False,False,False,False,False,False,False,False
W06000002,False,False,False,False,False,False,False,False
W06000001,False,False,False,False,False,False,False,False
S92000003,False,False,False,False,False,False,False,False
S92000003,False,False,False,False,False,False,False,False
S12000046,False,False,False,False,False,False,False,False
S12000045,False,False,False,False,False,False,False,False
S12000044,False,False,False,False,False,False,False,False
S12000042,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
E06000004,False,False,False,False,False,False,False,False
E06000003,False,False,False,False,False,False,False,False
E06000002,False,False,False,False,False,False,False,False
E06000001,False,False,False,False,False,False,False,False
95Z,False,False,False,False,False,False,False,False
95Y,False,False,False,False,False,False,False,False
95X,False,False,False,False,False,False,False,False
95W,False,False,False,False,False,False,False,False
95V,False,False,False,False,False,False,False,False
95U,False,False,False,False,False,False,False,False
95T,False,False,False,False,False,False,False,False
95S,False,False,False,False,False,False,False,False
95R,False,False,False,False,False,False,False,False
95Q,False,False,False,False,False,False,False,False
95P,False,False,False,False,False,False,False,False
95O,False,False,False,False,False,False,False,False
95N,False,False,False,False,False,False,False,False
95M,False,False,False,False,False,False,False,False
95L,False,False,False,False,False,False,False,False
95K,False,False,False,False,False,False,False,False
95J,False,False,False,False,False,False,False,False
95I,False,False,False,False,False,False,False,False
95H,False,False,False,False,False,False,False,False
95G,False,False,False,False,False,False,False,False
95F,False,False,False,False,False,False,False,False
95E,False,False,False,False,False,False,False,False
95D,False,False,False,False,False,False,False,False
95C,False,False,False,False,False,False,False,False
95B,False,False,False,False,False,False,False,False
95A,False,False,False,False,False,False,False,False

In [64]:
pop.dtypes

population                           float64
Males                                float64
Females                              float64
Lives in a household                 float64
Lives in a communal establishment    float64
Schoolchild                          float64
Area                                 float64
Density                              float64
dtype: object

In [82]:
pop.info()

<class 'pandas.core.frame.DataFrame'>
Index: 461 entries, W92000004 to 95A
Data columns (total 8 columns):
population                           461 non-null float64
Males                                461 non-null float64
Females                              461 non-null float64
Lives in a household                 461 non-null float64
Lives in a communal establishment    461 non-null float64
Schoolchild                          461 non-null float64
Area                                 461 non-null float64
Density                              461 non-null float64
dtypes: float64(8)
memory usage: 32.4+ KB

In [83]:
pop['population'].astype('int')

Area code
W92000004     3063456
W92000004     3063456
W06000024       58802
W06000023      132976
W06000022      145736
W06000021       91323
W06000020       91075
W06000019       69814
W06000018      178806
W06000016      234410
W06000015      346090
W06000014      126336
W06000013      139178
W06000012      139812
W06000011      239023
W06000010      183777
W06000009      122439
W06000008       75922
W06000006      134844
W06000005      152506
W06000004       93734
W06000003      115228
W06000002      121874
W06000001       69751
S92000003     5295403
S92000003     5295403
S12000046      593245
S12000045      105026
S12000044      337727
S12000042      147268
               ...
E06000004      191610
E06000003      135177
E06000002      138412
E06000001       92028
95Z            280962
95Y             67242
95X             78078
95W             78937
95V             39114
95U             85139
95T             53428
95S            120165
95R             69731
95Q             48339
95P             99480
95O             59340
95N             93023
95M             57852
95L             61805
95K             51356
95J             39843
95I             37013
95H             45038
95G             64044
95F             32180
95E             17050
95D             31224
95C             59067
95B             33536
95A            107877
Name: population, Length: 461, dtype: int64

In [84]:
pop.dtypes

population                           float64
Males                                float64
Females                              float64
Lives in a household                 float64
Lives in a communal establishment    float64
Schoolchild                          float64
Area                                 float64
Density                              float64
dtype: object

In [85]:
pop["population"] = pop['population'].astype('int')
pop.dtypes

population                             int64
Males                                float64
Females                              float64
Lives in a household                 float64
Lives in a communal establishment    float64
Schoolchild                          float64
Area                                 float64
Density                              float64
dtype: object

In [86]:
pop.head()

,population,Males,Females,Lives in a household,Lives in a communal establishment,Schoolchild,Area,Density
Area code,,,,,,,,
W92000004,3063456,1504228.0,1559228.0,3011182.0,52274.0,35061.0,2073511.0,1.5
W92000004,3063456,1504228.0,1559228.0,3011182.0,52274.0,35061.0,2073511.0,1.5
W06000024,58802,28791.0,30011.0,58334.0,468.0,474.0,11139.0,5.3
W06000023,132976,65683.0,67293.0,131047.0,1929.0,2117.0,518037.0,0.3
W06000022,145736,71380.0,74356.0,144103.0,1633.0,1509.0,19052.0,7.6

In [90]:
pop['Males'].astype('int')
pop['Females'].astype('int')
pop['Lives in a household'].astype('int')
pop['Lives in a communal establishment'].astype('int')

Area code
W92000004     52274
W92000004     52274
W06000024       468
W06000023      1929
W06000022      1633
W06000021      1629
W06000020       715
W06000019       575
W06000018      1051
W06000016      2525
W06000015     11539
W06000014      2077
W06000013      2336
W06000012      1130
W06000011      4660
W06000010      2550
W06000009      1894
W06000008      4478
W06000006      1600
W06000005       827
W06000004      1251
W06000003      2697
W06000002      3900
W06000001       810
S92000003     99017
S92000003     99017
S12000046     14994
S12000045       595
S12000044      2410
S12000042      5167
              ...
E06000004      3651
E06000003      1248
E06000002      2256
E06000001       937
95Z            4821
95Y             740
95X             595
95W            1462
95V             329
95U            1998
95T             888
95S            1640
95R            1017
95Q             294
95P             558
95O             702
95N             510
95M             390
95L             741
95K             484
95J             248
95I             302
95H             216
95G             641
95F             266
95E             143
95D             170
95C            1306
95B             686
95A            1377
Name: Lives in a communal establishment, Length: 461, dtype: int64

In [92]:
pop['Males']= pop['Males'].astype('int')
pop['Females']= pop['Females'].astype('int')
pop['Lives in a household']= pop['Lives in a household'].astype('int')
pop['Lives in a communal establishment']= pop['Lives in a communal establishment'].astype('int')

In [93]:
pop.dtypes

population                             int64
Males                                  int64
Females                                int64
Lives in a household                   int64
Lives in a communal establishment      int64
Schoolchild                          float64
Area                                 float64
Density                              float64
dtype: object

In [100]:
finaljoined=finaljoined.set_index('ladcd')
finaljoined.head(4)

,latitude,longitude,oa11cd,lsoa11cd,msoa11cd,lsoa11nm,msoa11nm,ladnm,FID
ladcd,,,,,,,,,
S12000033,57.144165,-2.114848,S00088970,S01006571,S02001247,West End North - 01,West End North,Aberdeen City,3015.0
S12000033,57.137880,-2.121487,S00089205,S01006576,S02001248,West End South - 02,West End South,Aberdeen City,3146.0
S12000033,57.124274,-2.127190,S00089357,S01006530,S02001239,Garthdee - 05,Garthdee,Aberdeen City,3489.0
S12000033,57.142701,-2.093295,S00090582,S01006587,S02001250,City Centre East - 01,City Centre East,Aberdeen City,3876.0

In [106]:
data=pd.read_csv('Postcode_coordinates.csv')

In [107]:
data.head(2)

,postcode,latitude,longitude,oa11cd,lsoa11cd,msoa11cd,ladcd,lsoa11nm,msoa11nm,ladnm,FID
0,AB10 1XG,57.144165,-2.114848,S00088970,S01006571,S02001247,S12000033,West End North - 01,West End North,Aberdeen City,3015.0
1,AB10 6RN,57.137880,-2.121487,S00089205,S01006576,S02001248,S12000033,West End South - 02,West End South,Aberdeen City,3146.0

In [108]:
data=data.set_index('ladcd')
data.head(4)

,postcode,latitude,longitude,oa11cd,lsoa11cd,msoa11cd,lsoa11nm,msoa11nm,ladnm,FID
ladcd,,,,,,,,,,
S12000033,AB10 1XG,57.144165,-2.114848,S00088970,S01006571,S02001247,West End North - 01,West End North,Aberdeen City,3015.0
S12000033,AB10 6RN,57.137880,-2.121487,S00089205,S01006576,S02001248,West End South - 02,West End South,Aberdeen City,3146.0
S12000033,AB10 7JB,57.124274,-2.127190,S00089357,S01006530,S02001239,Garthdee - 05,Garthdee,Aberdeen City,3489.0
S12000033,AB11 5QN,57.142701,-2.093295,S00090582,S01006587,S02001250,City Centre East - 01,City Centre East,Aberdeen City,3876.0

In [109]:
#merged = a.merge(b, on='ID')
result = pop.join(data)

In [110]:
result.head(4)

,population,Males,Females,Lives in a household,Lives in a communal establishment,Schoolchild,Area,Density,postcode,latitude,longitude,oa11cd,lsoa11cd,msoa11cd,lsoa11nm,msoa11nm,ladnm,FID
95A,107877,52648,55229,106500,1377,1560.0,37947.0,2.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95B,33536,16927,16609,32850,686,415.0,58526.0,0.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95C,59067,28742,30325,57761,1306,858.0,48299.0,1.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95D,31224,15442,15782,31054,170,374.0,41782.0,0.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [111]:
result.shape

(1642503, 18)

In [104]:
result.isna()

,population,Males,Females,Lives in a household,Lives in a communal establishment,Schoolchild,Area,Density,latitude,longitude,oa11cd,lsoa11cd,msoa11cd,lsoa11nm,msoa11nm,ladnm,FID
95A,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True
95B,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True
95C,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True
95D,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True
95E,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True
95F,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True
95G,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True
95H,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True
95I,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True
95J,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True
95K,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True
95L,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True
95M,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True
95N,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True
95O,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True
95P,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True
95Q,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True
95R,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True
95S,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True
95T,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True
95U,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True
95V,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True
95W,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True
95X,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True
95Y,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True
95Z,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True
E06000001,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
E06000001,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
E06000001,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
E06000001,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
W06000024,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
W06000024,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
W06000024,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
W06000024,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
W06000024,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
W06000024,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
W06000024,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
W06000024,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
W06000024,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
W06000024,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
W06000024,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
W06000024,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
W06000024,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
W06000024,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
W06000024,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
W06000024,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
W06000024,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
W06000024,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
W06000024,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
W06000024,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
W06000024,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
W06000024,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
W06000024,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
W06000024,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
W06000024,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
W06000024,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
W06000024,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
W06000024,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
W92000004,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True
W92000004,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True

In [115]:
resultpop=result.dropna()

In [116]:
resultpop.head(2)

,population,Males,Females,Lives in a household,Lives in a communal establishment,Schoolchild,Area,Density,postcode,latitude,longitude,oa11cd,lsoa11cd,msoa11cd,lsoa11nm,msoa11nm,ladnm,FID
E06000001,92028,44751,47277,91091,937,780.0,9386.0,9.8,TS27 4SX,54.681570,-1.210380,E00060531,E01011999,E02002489,Hartlepool 007D,Hartlepool 007,Hartlepool,2388382.0
E06000001,92028,44751,47277,91091,937,780.0,9386.0,9.8,TS27 3AR,54.710559,-1.273018,E00060316,E01011959,E02006909,Hartlepool 014A,Hartlepool 014,Hartlepool,2387696.0

In [117]:
resultpop.to_csv('population_postcode.csv',index=True)

In [113]:
urban = pd.read_csv('/Users/jyothigupta/Documents/UCL/Urbansimulation/week5/data/popincome.csv', na_values='')
urban.head(3)

        code                 label     pop  avg_income  med_income
0  E09000001        City of London   12000       92900       38300
1  E09000002  Barking and Dagenham   56000       18600       16200
2  E09000003                Barnet  159000       30400       18700

In [114]:
urban.shape

(33, 5)

In [120]:
SICdata.head(2)

,incorporationdate,postcode,companycategory,companystatus,CompanyCategory,CompanyStatus,IncorporationDate,SIC_2013,SIC2018,SICcombine
0,1992-05-12,SE4 1NQ,Private Limited Company,Active,Private Limited Company,Active,12/05/1992,90010,90010,90010.0
1,1999-07-22,TN11 9PL,Private Limited Company,Active,Private Limited Company,Active,22/07/1999,70229,70229,70229.0

In [121]:
SICpost=SICdata.set_index('postcode')
SICpost.head(4)

,incorporationdate,companycategory,companystatus,CompanyCategory,CompanyStatus,IncorporationDate,SIC_2013,SIC2018,SICcombine
postcode,,,,,,,,,
SE4 1NQ,1992-05-12,Private Limited Company,Active,Private Limited Company,Active,12/05/1992,90010,90010,90010.0
TN11 9PL,1999-07-22,Private Limited Company,Active,Private Limited Company,Active,22/07/1999,70229,70229,70229.0
GU21 5TS,2007-11-28,Private Limited Company,Active,Private Limited Company,Active,28/11/2007,99999,99999,99999.0
WD6 1JD,2008-01-15,Private Limited Company,Active,Private Limited Company,Active,15/01/2008,56101,56101,56101.0

In [122]:
resultpost=resultpop.set_index('postcode')
resultpost.head(4)

,population,Males,Females,Lives in a household,Lives in a communal establishment,Schoolchild,Area,Density,latitude,longitude,oa11cd,lsoa11cd,msoa11cd,lsoa11nm,msoa11nm,ladnm,FID
postcode,,,,,,,,,,,,,,,,,
TS27 4SX,92028,44751,47277,91091,937,780.0,9386.0,9.8,54.681570,-1.210380,E00060531,E01011999,E02002489,Hartlepool 007D,Hartlepool 007,Hartlepool,2388382.0
TS27 3AR,92028,44751,47277,91091,937,780.0,9386.0,9.8,54.710559,-1.273018,E00060316,E01011959,E02006909,Hartlepool 014A,Hartlepool 014,Hartlepool,2387696.0
TS27 3AS,92028,44751,47277,91091,937,780.0,9386.0,9.8,54.709460,-1.274327,E00060315,E01011959,E02006909,Hartlepool 014A,Hartlepool 014,Hartlepool,2387701.0
TS27 3AT,92028,44751,47277,91091,937,780.0,9386.0,9.8,54.709805,-1.279427,E00060315,E01011959,E02006909,Hartlepool 014A,Hartlepool 014,Hartlepool,2387707.0

In [123]:
SICpost.shape

(1148256, 9)

In [124]:
resultpost.shape

(1642413, 17)

In [125]:
complete = SICpost.join(resultpost)

In [126]:
complete.shape

(1148256, 26)

In [127]:
complete.head()

,incorporationdate,companycategory,companystatus,CompanyCategory,CompanyStatus,IncorporationDate,SIC_2013,SIC2018,SICcombine,population,...,Density,latitude,longitude,oa11cd,lsoa11cd,msoa11cd,lsoa11nm,msoa11nm,ladnm,FID
postcode,,,,,,,,,,,,,,,,,,,,,
06 830,2008-05-28,Limited Partnership,Active,Limited Partnership,Active,28/05/2008,0,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
06 830,2008-05-28,Limited Partnership,Active,Limited Partnership,Active,28/05/2008,0,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
06 830,2008-05-28,Limited Partnership,Active,Limited Partnership,Active,28/05/2008,0,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
06 830,2008-05-28,Limited Partnership,Active,Limited Partnership,Active,28/05/2008,0,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
06 830,2008-05-28,Limited Partnership,Active,Limited Partnership,Active,28/05/2008,0,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [129]:
comp=complete.dropna()

In [130]:
comp.head(2)

,incorporationdate,companycategory,companystatus,CompanyCategory,CompanyStatus,IncorporationDate,SIC_2013,SIC2018,SICcombine,population,...,Density,latitude,longitude,oa11cd,lsoa11cd,msoa11cd,lsoa11nm,msoa11nm,ladnm,FID
postcode,,,,,,,,,,,,,,,,,,,,,
AB10 1BA,2008-12-08,"PRI/LTD BY GUAR/NSC (Private, limited by guara...",Active,"PRI/LTD BY GUAR/NSC (Private, limited by guara...",Active,08/12/2008,82990,82990,82990.0,222793.0,...,12.0,57.148832,-2.098451,S00090540,S01006646,S02001261,George Street - 02,George Street,Aberdeen City,2688.0
AB10 1BA,2006-06-13,Private Limited Company,Active,Private Limited Company,Active,13/06/2006,58142,58142,58142.0,222793.0,...,12.0,57.148832,-2.098451,S00090540,S01006646,S02001261,George Street - 02,George Street,Aberdeen City,2688.0

In [131]:
comp.dtypes

incorporationdate                     object
companycategory                       object
companystatus                         object
CompanyCategory                       object
CompanyStatus                         object
IncorporationDate                     object
SIC_2013                               int64
SIC2018                                int64
SICcombine                           float64
population                           float64
Males                                float64
Females                              float64
Lives in a household                 float64
Lives in a communal establishment    float64
Schoolchild                          float64
Area                                 float64
Density                              float64
latitude                             float64
longitude                            float64
oa11cd                                object
lsoa11cd                              object
msoa11cd                              object
lsoa11nm                              object
msoa11nm                              object
ladnm                                 object
FID                                  float64
dtype: object

In [132]:
comp['population']= comp['population'].astype('int')
comp['SICcombine']= comp['SICcombine'].astype('int')
comp['Males']= comp['Males'].astype('int')
comp['Females']= comp['Females'].astype('int')

/Users/jyothigupta/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/Users/jyothigupta/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/jyothigupta/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/jyothigupta/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [133]:
comp.dtypes

incorporationdate                     object
companycategory                       object
companystatus                         object
CompanyCategory                       object
CompanyStatus                         object
IncorporationDate                     object
SIC_2013                               int64
SIC2018                                int64
SICcombine                             int64
population                             int64
Males                                  int64
Females                                int64
Lives in a household                 float64
Lives in a communal establishment    float64
Schoolchild                          float64
Area                                 float64
Density                              float64
latitude                             float64
longitude                            float64
oa11cd                                object
lsoa11cd                              object
msoa11cd                              object
lsoa11nm                              object
msoa11nm                              object
ladnm                                 object
FID                                  float64
dtype: object

In [134]:
comp.to_csv('complete.csv',index=True)